- name: Drupal mysql playbook
  become: yes
  gather_facts: no
  hosts: tlv-host4
  
  tasks:
    - name: Get usename
      ansible.builtin.shell: pwd
      register: result
    - ansible.builtin.debug:
        msg: "The current path is {{result.stdout}}"