- name: Keycloak playbook
  become: yes
  hosts: tlv-host5
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pip_install_packages:
      - name: docker

  
  roles:
    # - geerlingguy.pip
    # - geerlingguy.docker
    - keycloak