    - name: Ensure directory exists
      become: true
      file:
        group: root
        owner: root
        path: "{{ service_directory.employee_app }}"
        state: directory
    - name: Log into DockerHub
      become: true
      community.docker.docker_login:
        username: "{{ docker_credentials.user }}"
        password: "{{ docker_credentials.password }}"
    - name: Pull image and run container
      docker_container:
        name: employee-intranet
        image: caty/tlv-intranet-employee:latest
        state: started
        recreate: yes
        detach: true
        pull: yes
        #restart_policy: unless-stopped
        ports:
          - "8080:8080"
    - name: Log out of DockerHub
      community.docker.docker_login:
        state: absent